// lib/JSearch.js
const API_BASE_URL = "/api";

export async function searchJobs(params = {}) {
  const queryString = new URLSearchParams(params).toString();
  const response = await fetch(`${API_BASE_URL}/jobs?${queryString}`);

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.message || "Failed to fetch jobs");
  }

  return response.json();
}

export async function getJobDetails(job_id) {
  const response = await fetch(`${API_BASE_URL}/jobs/${job_id}`);

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.message || "Failed to fetch job details");
  }

  return response.json();
}

// Export the realistic jobs data
export const realisticJobs = [
  {
    job_id: "1",
    job_title: "Senior Software Engineer",
    employer_name: "Google",
    employer_logo: "https://logo.clearbit.com/google.com",
    job_description:
      "Design and implement scalable distributed systems for Google's core search infrastructure. Work with a team of engineers to solve complex problems at massive scale.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Mountain View",
    job_country: "United States",
    job_min_salary: 150000,
    job_max_salary: 220000,
    job_salary_currency: "USD",
    job_apply_link: "https://careers.google.com/jobs/results/1",
    job_posted_at_datetime_utc: "2023-05-15T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Bachelor's degree in Computer Science or related field",
        "5+ years of software development experience",
        "Expertise in Java, C++, or Python",
      ],
      Responsibilities: [
        "Design and implement large-scale distributed systems",
        "Mentor junior engineers",
        "Participate in code and design reviews",
      ],
      Benefits: [
        "Comprehensive health benefits",
        "401(k) matching",
        "On-site gym and meals",
      ],
    },
  },
  {
    job_id: "2",
    job_title: "Data Scientist",
    employer_name: "Amazon",
    employer_logo: "https://logo.clearbit.com/amazon.com",
    job_description:
      "Use statistical analysis and machine learning to improve Amazon's recommendation systems. Work with petabytes of data to uncover insights that drive business decisions.",
    job_employment_type: "FULLTIME",
    job_is_remote: true,
    job_city: "Seattle",
    job_country: "United States",
    job_min_salary: 120000,
    job_max_salary: 180000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.amazon.jobs/en/jobs/2",
    job_posted_at_datetime_utc: "2023-05-20T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "PhD or Master's in Statistics, Computer Science, or related field",
        "3+ years experience with machine learning",
        "Proficiency in Python and SQL",
      ],
      Responsibilities: [
        "Develop predictive models for customer behavior",
        "Analyze A/B test results",
        "Communicate findings to stakeholders",
      ],
    },
  },
  {
    job_id: "3",
    job_title: "Marketing Manager",
    employer_name: "Coca-Cola",
    employer_logo: "https://logo.clearbit.com/coca-cola.com",
    job_description:
      "Develop and execute marketing campaigns to drive brand awareness and sales. Collaborate with creative teams to deliver compelling advertising strategies.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Atlanta",
    job_country: "United States",
    job_min_salary: 90000,
    job_max_salary: 120000,
    job_salary_currency: "USD",
    job_apply_link: "https://careers.coca-colacompany.com/jobs/3",
    job_posted_at_datetime_utc: "2023-06-10T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Bachelor's degree in Marketing or Business Administration",
        "5+ years of marketing experience",
        "Strong analytical and communication skills",
      ],
      Responsibilities: [
        "Create and manage advertising campaigns",
        "Analyze market trends and customer insights",
        "Collaborate with sales and design teams",
      ],
    },
  },
  {
    job_id: "4",
    job_title: "Financial Analyst",
    employer_name: "JPMorgan Chase",
    employer_logo: "https://logo.clearbit.com/jpmorganchase.com",
    job_description:
      "Conduct financial modeling and analysis to support investment decisions. Prepare reports and forecasts for executive leadership.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "New York City",
    job_country: "United States",
    job_min_salary: 85000,
    job_max_salary: 110000,
    job_salary_currency: "USD",
    job_apply_link: "https://careers.jpmorgan.com/global/en/jobs/4",
    job_posted_at_datetime_utc: "2023-06-15T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Bachelor's degree in Finance or Economics",
        "3+ years of experience in financial analysis",
        "Proficiency in Excel and financial modeling software",
      ],
      Responsibilities: [
        "Analyze financial data and market trends",
        "Prepare investment reports for stakeholders",
        "Assist in budgeting and forecasting processes",
      ],
    },
  },
  {
    job_id: "5",
    job_title: "Registered Nurse",
    employer_name: "Mayo Clinic",
    employer_logo: "https://logo.clearbit.com/mayoclinic.org",
    job_description:
      "Provide direct patient care, assess health conditions, and administer treatment plans. Work in collaboration with healthcare teams to ensure patient safety and satisfaction.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Rochester",
    job_country: "United States",
    job_min_salary: 70000,
    job_max_salary: 95000,
    job_salary_currency: "USD",
    job_apply_link: "https://jobs.mayoclinic.org/job/5",
    job_posted_at_datetime_utc: "2023-07-01T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Bachelor's or Associate's degree in Nursing",
        "Active RN license",
        "Experience in acute care settings",
      ],
      Responsibilities: [
        "Monitor patient health and vital signs",
        "Administer medications and treatments",
        "Educate patients and families on healthcare plans",
      ],
    },
  },
  {
    job_id: "6",
    job_title: "UX Designer",
    employer_name: "Adobe",
    employer_logo: "https://logo.clearbit.com/adobe.com",
    job_description:
      "Design intuitive user experiences for Adobe's creative cloud products. Conduct user research and collaborate with product teams to create beautiful, functional interfaces.",
    job_employment_type: "FULLTIME",
    job_is_remote: true,
    job_city: "San Francisco",
    job_country: "United States",
    job_min_salary: 110000,
    job_max_salary: 160000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.adobe.com/careers/6",
    job_posted_at_datetime_utc: "2023-07-10T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Portfolio demonstrating UX design skills",
        "3+ years experience in product design",
        "Familiarity with Figma and Adobe XD",
      ],
      Responsibilities: [
        "Create wireframes and prototypes",
        "Conduct user testing sessions",
        "Collaborate with engineering teams",
      ],
    },
  },
  {
    job_id: "7",
    job_title: "Mechanical Engineer",
    employer_name: "Tesla",
    employer_logo: "https://logo.clearbit.com/tesla.com",
    job_description:
      "Design and test mechanical components for Tesla's electric vehicles. Work on innovative solutions to improve vehicle performance and manufacturing efficiency.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Fremont",
    job_country: "United States",
    job_min_salary: 95000,
    job_max_salary: 140000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.tesla.com/careers/7",
    job_posted_at_datetime_utc: "2023-07-15T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Bachelor's degree in Mechanical Engineering",
        "2+ years of product design experience",
        "Proficiency with CAD software",
      ],
      Responsibilities: [
        "Design vehicle components and systems",
        "Conduct stress and thermal analysis",
        "Collaborate with manufacturing teams",
      ],
    },
  },
  {
    job_id: "8",
    job_title: "Content Strategist",
    employer_name: "Netflix",
    employer_logo: "https://logo.clearbit.com/netflix.com",
    job_description:
      "Develop content strategies to engage Netflix's global audience. Analyze viewer data to inform content creation and marketing decisions.",
    job_employment_type: "FULLTIME",
    job_is_remote: true,
    job_city: "Los Gatos",
    job_country: "United States",
    job_min_salary: 100000,
    job_max_salary: 150000,
    job_salary_currency: "USD",
    job_apply_link: "https://jobs.netflix.com/jobs/8",
    job_posted_at_datetime_utc: "2023-07-20T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Bachelor's degree in Communications or related field",
        "4+ years in content strategy or digital marketing",
        "Strong analytical skills",
      ],
      Responsibilities: [
        "Develop content calendars and strategies",
        "Analyze audience engagement metrics",
        "Collaborate with creative teams worldwide",
      ],
    },
  },
  {
    job_id: "9",
    job_title: "Cybersecurity Analyst",
    employer_name: "IBM",
    employer_logo: "https://logo.clearbit.com/ibm.com",
    job_description:
      "Protect IBM's systems and client data from security threats. Monitor networks, investigate incidents, and implement security measures.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Armonk",
    job_country: "United States",
    job_min_salary: 105000,
    job_max_salary: 155000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.ibm.com/careers/us-en/jobs/9",
    job_posted_at_datetime_utc: "2023-08-01T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Bachelor's degree in Cybersecurity or related field",
        "Certifications like CISSP or CEH preferred",
        "Experience with SIEM tools",
      ],
      Responsibilities: [
        "Monitor systems for security breaches",
        "Investigate security incidents",
        "Implement security protocols",
      ],
    },
  },
  {
    job_id: "10",
    job_title: "HR Business Partner",
    employer_name: "Microsoft",
    employer_logo: "https://logo.clearbit.com/microsoft.com",
    job_description:
      "Support Microsoft's engineering teams with HR strategy and employee relations. Partner with leadership to develop talent and foster an inclusive culture.",
    job_employment_type: "FULLTIME",
    job_is_remote: true,
    job_city: "Redmond",
    job_country: "United States",
    job_min_salary: 95000,
    job_max_salary: 135000,
    job_salary_currency: "USD",
    job_apply_link: "https://careers.microsoft.com/professionals/us/en/job/10",
    job_posted_at_datetime_utc: "2023-08-05T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Bachelor's degree in HR or related field",
        "5+ years HR experience in tech",
        "Knowledge of employment laws",
      ],
      Responsibilities: [
        "Advise managers on HR policies",
        "Support employee development programs",
        "Analyze workforce metrics",
      ],
    },
  },
  {
    job_id: "11",
    job_title: "Frontend Developer",
    employer_name: "Spotify",
    employer_logo: "https://logo.clearbit.com/spotify.com",
    job_description:
      "Build engaging user interfaces for Spotify's web applications using React. Collaborate with designers to implement pixel-perfect UIs that delight millions of users worldwide.",
    job_employment_type: "FULLTIME",
    job_is_remote: true,
    job_city: "New York",
    job_country: "United States",
    job_min_salary: 110000,
    job_max_salary: 160000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.lifeatspotify.com/jobs/11",
    job_posted_at_datetime_utc: "2023-08-10T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "3+ years experience with React",
        "Strong JavaScript/TypeScript skills",
        "Experience with modern CSS frameworks",
      ],
      Responsibilities: [
        "Develop new user-facing features",
        "Optimize components for performance",
        "Write clean, maintainable code",
      ],
    },
  },
  {
    job_id: "12",
    job_title: "DevOps Engineer",
    employer_name: "Uber",
    employer_logo: "https://logo.clearbit.com/uber.com",
    job_description:
      "Design and maintain Uber's cloud infrastructure to ensure high availability and scalability. Automate deployment processes and implement monitoring solutions.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "San Francisco",
    job_country: "United States",
    job_min_salary: 130000,
    job_max_salary: 190000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.uber.com/careers/12",
    job_posted_at_datetime_utc: "2023-08-15T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Experience with AWS/GCP",
        "Knowledge of Kubernetes and Docker",
        "CI/CD pipeline expertise",
      ],
      Responsibilities: [
        "Manage cloud infrastructure",
        "Implement automation tools",
        "Monitor system performance",
      ],
    },
  },
  {
    job_id: "13",
    job_title: "Product Manager",
    employer_name: "Airbnb",
    employer_logo: "https://logo.clearbit.com/airbnb.com",
    job_description:
      "Lead product development for Airbnb's host tools. Define product vision, gather requirements, and work with cross-functional teams to deliver exceptional user experiences.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "San Francisco",
    job_country: "United States",
    job_min_salary: 120000,
    job_max_salary: 180000,
    job_salary_currency: "USD",
    job_apply_link: "https://careers.airbnb.com/13",
    job_posted_at_datetime_utc: "2023-08-20T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "3+ years product management experience",
        "Technical background preferred",
        "Strong analytical skills",
      ],
      Responsibilities: [
        "Define product roadmap",
        "Collaborate with engineering and design",
        "Analyze market trends",
      ],
    },
  },
  {
    job_id: "14",
    job_title: "AI Research Scientist",
    employer_name: "OpenAI",
    employer_logo: "https://logo.clearbit.com/openai.com",
    job_description:
      "Conduct cutting-edge research in machine learning and artificial intelligence. Publish findings and contribute to OpenAI's mission of ensuring AGI benefits all of humanity.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "San Francisco",
    job_country: "United States",
    job_min_salary: 200000,
    job_max_salary: 300000,
    job_salary_currency: "USD",
    job_apply_link: "https://openai.com/careers/14",
    job_posted_at_datetime_utc: "2023-08-25T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "PhD in Computer Science or related field",
        "Publications in top ML conferences",
        "Strong programming skills",
      ],
      Responsibilities: [
        "Conduct original AI research",
        "Develop novel algorithms",
        "Collaborate with research team",
      ],
    },
  },
  {
    job_id: "15",
    job_title: "Sales Executive",
    employer_name: "Salesforce",
    employer_logo: "https://logo.clearbit.com/salesforce.com",
    job_description:
      "Drive enterprise sales of Salesforce's CRM solutions. Build relationships with key decision makers and help businesses transform their customer engagement strategies.",
    job_employment_type: "FULLTIME",
    job_is_remote: true,
    job_city: "Chicago",
    job_country: "United States",
    job_min_salary: 80000,
    job_max_salary: 160000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.salesforce.com/company/careers/15",
    job_posted_at_datetime_utc: "2023-09-01T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Proven sales experience",
        "Excellent communication skills",
        "Knowledge of SaaS industry",
      ],
      Responsibilities: [
        "Identify new business opportunities",
        "Manage sales pipeline",
        "Achieve quarterly targets",
      ],
    },
  },
  {
    job_id: "16",
    job_title: "Cloud Architect",
    employer_name: "Oracle",
    employer_logo: "https://logo.clearbit.com/oracle.com",
    job_description:
      "Design and implement cloud solutions for enterprise clients using Oracle Cloud Infrastructure. Provide technical leadership and guidance to development teams.",
    job_employment_type: "FULLTIME",
    job_is_remote: true,
    job_city: "Austin",
    job_country: "United States",
    job_min_salary: 140000,
    job_max_salary: 210000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.oracle.com/careers/16",
    job_posted_at_datetime_utc: "2023-09-05T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "10+ years IT experience",
        "OCI/AWS/Azure certification",
        "Strong architecture skills",
      ],
      Responsibilities: [
        "Design cloud solutions",
        "Advise clients on best practices",
        "Mentor junior architects",
      ],
    },
  },
  {
    job_id: "17",
    job_title: "Technical Writer",
    employer_name: "GitHub",
    employer_logo: "https://logo.clearbit.com/github.com",
    job_description:
      "Create clear, comprehensive documentation for GitHub's developer tools and APIs. Work closely with product teams to explain complex technical concepts to diverse audiences.",
    job_employment_type: "FULLTIME",
    job_is_remote: true,
    job_city: "San Francisco",
    job_country: "United States",
    job_min_salary: 90000,
    job_max_salary: 130000,
    job_salary_currency: "USD",
    job_apply_link: "https://github.com/about/careers/17",
    job_posted_at_datetime_utc: "2023-09-10T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Technical background",
        "Excellent writing skills",
        "Experience with docs-as-code",
      ],
      Responsibilities: [
        "Write API documentation",
        "Create tutorials and guides",
        "Maintain knowledge base",
      ],
    },
  },
  {
    job_id: "18",
    job_title: "Game Developer",
    employer_name: "Electronic Arts",
    employer_logo: "https://logo.clearbit.com/ea.com",
    job_description:
      "Develop gameplay systems for EA's next-generation sports titles. Work with artists and designers to create immersive gaming experiences for millions of players.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Vancouver",
    job_country: "Canada",
    job_min_salary: 85000,
    job_max_salary: 120000,
    job_salary_currency: "CAD",
    job_apply_link: "https://www.ea.com/careers/18",
    job_posted_at_datetime_utc: "2023-09-15T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Experience with Unity/Unreal",
        "C++/C# proficiency",
        "Passion for gaming",
      ],
      Responsibilities: [
        "Implement game features",
        "Optimize game performance",
        "Fix bugs and issues",
      ],
    },
  },
  {
    job_id: "19",
    job_title: "Blockchain Developer",
    employer_name: "Coinbase",
    employer_logo: "https://logo.clearbit.com/coinbase.com",
    job_description:
      "Build decentralized applications on blockchain platforms. Contribute to Coinbase's mission of creating an open financial system for the world.",
    job_employment_type: "FULLTIME",
    job_is_remote: true,
    job_city: "San Francisco",
    job_country: "United States",
    job_min_salary: 150000,
    job_max_salary: 220000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.coinbase.com/careers/19",
    job_posted_at_datetime_utc: "2023-09-20T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Solidity/Rust experience",
        "Understanding of cryptography",
        "Web3.js/ethers.js knowledge",
      ],
      Responsibilities: [
        "Develop smart contracts",
        "Design blockchain protocols",
        "Ensure security best practices",
      ],
    },
  },
  {
    job_id: "20",
    job_title: "iOS Developer",
    employer_name: "Twitter",
    employer_logo: "https://logo.clearbit.com/twitter.com",
    job_description:
      "Create elegant, performant iOS applications for Twitter. Work with SwiftUI to build features used by millions of people every day.",
    job_employment_type: "FULLTIME",
    job_is_remote: true,
    job_city: "San Francisco",
    job_country: "United States",
    job_min_salary: 120000,
    job_max_salary: 180000,
    job_salary_currency: "USD",
    job_apply_link: "https://careers.twitter.com/20",
    job_posted_at_datetime_utc: "2023-09-25T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Swift/SwiftUI expertise",
        "Published apps in App Store",
        "UIKit knowledge",
      ],
      Responsibilities: [
        "Implement new features",
        "Optimize app performance",
        "Fix bugs and crashes",
      ],
    },
  },
  {
    job_id: "21",
    job_title: "Cloud Security Engineer",
    employer_name: "Palo Alto Networks",
    employer_logo: "https://logo.clearbit.com/paloaltonetworks.com",
    job_description:
      "Secure cloud environments for enterprise clients. Implement security controls and monitor for threats across AWS, Azure, and GCP platforms.",
    job_employment_type: "FULLTIME",
    job_is_remote: true,
    job_city: "Santa Clara",
    job_country: "United States",
    job_min_salary: 130000,
    job_max_salary: 190000,
    job_salary_currency: "USD",
    job_apply_link: "https://jobs.paloaltonetworks.com/21",
    job_posted_at_datetime_utc: "2023-10-01T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Cloud security certifications",
        "Experience with CSPM tools",
        "Knowledge of compliance frameworks",
      ],
      Responsibilities: [
        "Implement security controls",
        "Conduct risk assessments",
        "Respond to security incidents",
      ],
    },
  },
  {
    job_id: "22",
    job_title: "Technical Recruiter",
    employer_name: "LinkedIn",
    employer_logo: "https://logo.clearbit.com/linkedin.com",
    job_description:
      "Source and recruit top technical talent for LinkedIn's engineering teams. Build relationships with candidates and hiring managers to ensure successful placements.",
    job_employment_type: "FULLTIME",
    job_is_remote: true,
    job_city: "Sunnyvale",
    job_country: "United States",
    job_min_salary: 95000,
    job_max_salary: 140000,
    job_salary_currency: "USD",
    job_apply_link: "https://careers.linkedin.com/22",
    job_posted_at_datetime_utc: "2023-10-05T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Technical recruiting experience",
        "Knowledge of tech stack",
        "Strong sourcing skills",
      ],
      Responsibilities: [
        "Source passive candidates",
        "Conduct technical screenings",
        "Manage hiring process",
      ],
    },
  },
  {
    job_id: "23",
    job_title: "AR/VR Developer",
    employer_name: "Meta",
    employer_logo: "https://logo.clearbit.com/meta.com",
    job_description:
      "Build immersive experiences for Meta's virtual reality platforms. Work with cutting-edge technology to define the future of social interaction in the metaverse.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Menlo Park",
    job_country: "United States",
    job_min_salary: 140000,
    job_max_salary: 200000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.metacareers.com/jobs/23",
    job_posted_at_datetime_utc: "2023-10-10T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Unity/Unreal experience",
        "3D math skills",
        "C++/C# proficiency",
      ],
      Responsibilities: [
        "Develop VR applications",
        "Optimize for performance",
        "Collaborate with 3D artists",
      ],
    },
  },
  {
    job_id: "24",
    job_title: "Data Engineer",
    employer_name: "Stripe",
    employer_logo: "https://logo.clearbit.com/stripe.com",
    job_description:
      "Build and maintain Stripe's data infrastructure. Design scalable data pipelines that process billions of transactions with high reliability.",
    job_employment_type: "FULLTIME",
    job_is_remote: true,
    job_city: "San Francisco",
    job_country: "United States",
    job_min_salary: 150000,
    job_max_salary: 210000,
    job_salary_currency: "USD",
    job_apply_link: "https://stripe.com/jobs/24",
    job_posted_at_datetime_utc: "2023-10-15T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Experience with Spark/Flink",
        "SQL and data modeling skills",
        "Python/Java/Scala knowledge",
      ],
      Responsibilities: [
        "Build ETL pipelines",
        "Optimize data storage",
        "Ensure data quality",
      ],
    },
  },
  {
    job_id: "25",
    job_title: "Customer Success Manager",
    employer_name: "Zoom",
    employer_logo: "https://logo.clearbit.com/zoom.us",
    job_description:
      "Ensure customer satisfaction and adoption of Zoom's communication platform. Work with enterprise clients to maximize the value they get from Zoom products.",
    job_employment_type: "FULLTIME",
    job_is_remote: true,
    job_city: "San Jose",
    job_country: "United States",
    job_min_salary: 85000,
    job_max_salary: 120000,
    job_salary_currency: "USD",
    job_apply_link: "https://careers.zoom.us/25",
    job_posted_at_datetime_utc: "2023-10-20T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Customer success experience",
        "Technical aptitude",
        "Excellent communication skills",
      ],
      Responsibilities: [
        "Onboard new customers",
        "Conduct business reviews",
        "Identify expansion opportunities",
      ],
    },
  },
  {
    job_id: "26",
    job_title: "Backend Engineer",
    employer_name: "Pinterest",
    employer_logo: "https://logo.clearbit.com/pinterest.com",
    job_description:
      "Develop scalable backend services for Pinterest's discovery platform. Work with large datasets to deliver personalized content to millions of users.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "San Francisco",
    job_country: "United States",
    job_min_salary: 130000,
    job_max_salary: 180000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.pinterestcareers.com/jobs/26",
    job_posted_at_datetime_utc: "2023-10-25T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Java/Go/Python experience",
        "Distributed systems knowledge",
        "Database optimization skills",
      ],
      Responsibilities: [
        "Design microservices",
        "Improve API performance",
        "Troubleshoot production issues",
      ],
    },
  },
  {
    job_id: "27",
    job_title: "QA Automation Engineer",
    employer_name: "Atlassian",
    employer_logo: "https://logo.clearbit.com/atlassian.com",
    job_description:
      "Build automated test frameworks for Atlassian's productivity tools. Ensure high software quality through comprehensive test coverage and CI/CD integration.",
    job_employment_type: "FULLTIME",
    job_is_remote: true,
    job_city: "Sydney",
    job_country: "Australia",
    job_min_salary: 100000,
    job_max_salary: 140000,
    job_salary_currency: "AUD",
    job_apply_link: "https://www.atlassian.com/company/careers/27",
    job_posted_at_datetime_utc: "2023-11-01T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Selenium/Cypress experience",
        "Programming skills (Java/Python)",
        "CI/CD pipeline knowledge",
      ],
      Responsibilities: [
        "Write automated tests",
        "Maintain test infrastructure",
        "Analyze test results",
      ],
    },
  },
  {
    job_id: "28",
    job_title: "Technical Support Engineer",
    employer_name: "Shopify",
    employer_logo: "https://logo.clearbit.com/shopify.com",
    job_description:
      "Provide expert technical support to Shopify merchants. Troubleshoot complex issues and work with engineering teams to resolve product bugs.",
    job_employment_type: "FULLTIME",
    job_is_remote: true,
    job_city: "Ottawa",
    job_country: "Canada",
    job_min_salary: 75000,
    job_max_salary: 100000,
    job_salary_currency: "CAD",
    job_apply_link: "https://www.shopify.com/careers/28",
    job_posted_at_datetime_utc: "2023-11-05T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Technical troubleshooting skills",
        "Patience and empathy",
        "Web technologies knowledge",
      ],
      Responsibilities: [
        "Resolve merchant issues",
        "Document solutions",
        "Escalate bugs to engineering",
      ],
    },
  },
  {
    job_id: "29",
    job_title: "Machine Learning Engineer",
    employer_name: "TikTok",
    employer_logo: "https://logo.clearbit.com/tiktok.com",
    job_description:
      "Develop recommendation algorithms for TikTok's content feed. Apply deep learning techniques to personalize the user experience for billions of videos.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Los Angeles",
    job_country: "United States",
    job_min_salary: 160000,
    job_max_salary: 230000,
    job_salary_currency: "USD",
    job_apply_link: "https://careers.tiktok.com/29",
    job_posted_at_datetime_utc: "2023-11-10T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "PyTorch/TensorFlow experience",
        "Strong math background",
        "Distributed systems knowledge",
      ],
      Responsibilities: [
        "Train ML models",
        "Optimize recommendation algorithms",
        "Analyze model performance",
      ],
    },
  },
  {
    job_id: "30",
    job_title: "Full Stack Developer",
    employer_name: "Slack",
    employer_logo: "https://logo.clearbit.com/slack.com",
    job_description:
      "Build features for Slack's communication platform using modern web technologies. Work across the stack to deliver seamless user experiences.",
    job_employment_type: "FULLTIME",
    job_is_remote: true,
    job_city: "San Francisco",
    job_country: "United States",
    job_min_salary: 120000,
    job_max_salary: 180000,
    job_salary_currency: "USD",
    job_apply_link: "https://slack.com/careers/30",
    job_posted_at_datetime_utc: "2023-11-15T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "JavaScript/TypeScript expertise",
        "React/Node.js experience",
        "Database knowledge",
      ],
      Responsibilities: [
        "Implement new features",
        "Write clean, tested code",
        "Participate in code reviews",
      ],
    },
  },
  {
    job_id: "31",
    job_title: "Executive Chef",
    employer_name: "Marriott International",
    employer_logo: "https://logo.clearbit.com/marriott.com",
    job_description:
      "Lead kitchen operations for a luxury hotel restaurant. Create innovative menus, manage culinary staff, and maintain exceptional food quality standards.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "New York",
    job_country: "United States",
    job_min_salary: 70000,
    job_max_salary: 110000,
    job_salary_currency: "USD",
    job_apply_link: "https://jobs.marriott.com/31",
    job_posted_at_datetime_utc: "2023-11-20T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Culinary degree or equivalent experience",
        "5+ years kitchen management",
        "Food safety certification",
      ],
      Responsibilities: [
        "Menu development and costing",
        "Kitchen staff supervision",
        "Quality control",
      ],
    },
  },
  {
    job_id: "32",
    job_title: "Fashion Buyer",
    employer_name: "Nordstrom",
    employer_logo: "https://logo.clearbit.com/nordstrom.com",
    job_description:
      "Curate fashion collections for Nordstrom's women's apparel department. Analyze trends, negotiate with vendors, and optimize inventory turnover.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Seattle",
    job_country: "United States",
    job_min_salary: 65000,
    job_max_salary: 95000,
    job_salary_currency: "USD",
    job_apply_link: "https://careers.nordstrom.com/32",
    job_posted_at_datetime_utc: "2023-11-25T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Degree in Fashion Merchandising",
        "3+ years buying experience",
        "Strong negotiation skills",
      ],
      Responsibilities: [
        "Select seasonal collections",
        "Manage vendor relationships",
        "Analyze sales data",
      ],
    },
  },
  {
    job_id: "33",
    job_title: "Wildlife Biologist",
    employer_name: "National Park Service",
    employer_logo: "https://logo.clearbit.com/nps.gov",
    job_description:
      "Conduct field research on wildlife populations in Yellowstone National Park. Monitor endangered species and develop conservation strategies.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Yellowstone",
    job_country: "United States",
    job_min_salary: 55000,
    job_max_salary: 85000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.usajobs.gov/33",
    job_posted_at_datetime_utc: "2023-11-30T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Master's in Wildlife Biology",
        "Field research experience",
        "Species identification skills",
      ],
      Responsibilities: [
        "Conduct population surveys",
        "Track migration patterns",
        "Prepare scientific reports",
      ],
    },
  },
  {
    job_id: "34",
    job_title: "Event Planner",
    employer_name: "Prestige Events",
    employer_logo: "https://logo.clearbit.com/prestigeevents.com",
    job_description:
      "Coordinate high-end corporate and social events. Manage all aspects from venue selection to vendor coordination and day-of execution.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Miami",
    job_country: "United States",
    job_min_salary: 50000,
    job_max_salary: 75000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.prestigeevents.com/careers/34",
    job_posted_at_datetime_utc: "2023-12-05T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "3+ years event planning",
        "Budget management skills",
        "Vendor network",
      ],
      Responsibilities: [
        "Client consultations",
        "Timeline management",
        "On-site coordination",
      ],
    },
  },
  {
    job_id: "35",
    job_title: "Physical Therapist",
    employer_name: "Mayo Clinic",
    employer_logo: "https://logo.clearbit.com/mayoclinic.org",
    job_description:
      "Provide rehabilitation services to patients recovering from injuries or surgeries. Develop personalized treatment plans and monitor progress.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Rochester",
    job_country: "United States",
    job_min_salary: 75000,
    job_max_salary: 100000,
    job_salary_currency: "USD",
    job_apply_link: "https://jobs.mayoclinic.org/35",
    job_posted_at_datetime_utc: "2023-12-10T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "DPT degree",
        "State licensure",
        "2+ years clinical experience",
      ],
      Responsibilities: [
        "Patient assessments",
        "Treatment plan development",
        "Progress documentation",
      ],
    },
  },
  {
    job_id: "36",
    job_title: "Commercial Pilot",
    employer_name: "Delta Airlines",
    employer_logo: "https://logo.clearbit.com/delta.com",
    job_description:
      "Fly domestic and international routes for a major airline. Ensure passenger safety and adhere to all FAA regulations and company procedures.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Atlanta",
    job_country: "United States",
    job_min_salary: 120000,
    job_max_salary: 250000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.delta.com/us/en/careers/36",
    job_posted_at_datetime_utc: "2023-12-15T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "ATP certificate",
        "1500+ flight hours",
        "First Class Medical",
      ],
      Responsibilities: [
        "Pre-flight preparations",
        "Aircraft operation",
        "Crew coordination",
      ],
    },
  },
  {
    job_id: "37",
    job_title: "Architect",
    employer_name: "Gensler",
    employer_logo: "https://logo.clearbit.com/gensler.com",
    job_description:
      "Design innovative commercial spaces for a leading architecture firm. Lead projects from concept through construction documentation.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "San Francisco",
    job_country: "United States",
    job_min_salary: 80000,
    job_max_salary: 120000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.gensler.com/careers/37",
    job_posted_at_datetime_utc: "2023-12-20T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Professional architecture degree",
        "Licensure preferred",
        "Revit proficiency",
      ],
      Responsibilities: [
        "Concept development",
        "Construction drawings",
        "Client presentations",
      ],
    },
  },
  {
    job_id: "38",
    job_title: "High School Teacher",
    employer_name: "Chicago Public Schools",
    employer_logo: "https://logo.clearbit.com/cps.edu",
    job_description:
      "Teach mathematics to high school students. Develop lesson plans aligned with state standards and foster a positive learning environment.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Chicago",
    job_country: "United States",
    job_min_salary: 50000,
    job_max_salary: 80000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.cps.edu/careers/38",
    job_posted_at_datetime_utc: "2023-12-25T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Teaching certification",
        "Content area expertise",
        "Classroom management skills",
      ],
      Responsibilities: [
        "Lesson planning",
        "Student assessment",
        "Parent communication",
      ],
    },
  },
  {
    job_id: "39",
    job_title: "Construction Manager",
    employer_name: "Turner Construction",
    employer_logo: "https://logo.clearbit.com/turnerconstruction.com",
    job_description:
      "Oversee commercial construction projects from groundbreaking to completion. Manage subcontractors, budgets, and timelines.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Boston",
    job_country: "United States",
    job_min_salary: 90000,
    job_max_salary: 140000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.turnerconstruction.com/careers/39",
    job_posted_at_datetime_utc: "2023-12-30T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "5+ years construction experience",
        "OSHA certification",
        "Budget management skills",
      ],
      Responsibilities: [
        "Project scheduling",
        "Quality control",
        "Safety compliance",
      ],
    },
  },
  {
    job_id: "40",
    job_title: "Veterinarian",
    employer_name: "Banfield Pet Hospital",
    employer_logo: "https://logo.clearbit.com/banfield.com",
    job_description:
      "Provide compassionate care to pets in a busy animal hospital. Perform examinations, diagnose conditions, and perform surgeries.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Denver",
    job_country: "United States",
    job_min_salary: 90000,
    job_max_salary: 130000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.banfield.com/careers/40",
    job_posted_at_datetime_utc: "2024-01-05T09:00:00Z",
    job_highlights: {
      Qualifications: ["DVM degree", "State licensure", "Surgical experience"],
      Responsibilities: [
        "Animal examinations",
        "Diagnostic testing",
        "Client education",
      ],
    },
  },
  {
    job_id: "41",
    job_title: "Journalist",
    employer_name: "The Washington Post",
    employer_logo: "https://logo.clearbit.com/washingtonpost.com",
    job_description:
      "Cover national politics for a major newspaper. Conduct investigations, interview sources, and write compelling news stories.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Washington DC",
    job_country: "United States",
    job_min_salary: 60000,
    job_max_salary: 90000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.washingtonpost.com/careers/41",
    job_posted_at_datetime_utc: "2024-01-10T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Degree in Journalism",
        "5+ years reporting experience",
        "Strong writing portfolio",
      ],
      Responsibilities: [
        "Research stories",
        "Conduct interviews",
        "Meet deadlines",
      ],
    },
  },
  {
    job_id: "42",
    job_title: "Interior Designer",
    employer_name: "HOK",
    employer_logo: "https://logo.clearbit.com/hok.com",
    job_description:
      "Create functional and aesthetically pleasing spaces for corporate clients. Select finishes, furniture, and lighting solutions.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "New York",
    job_country: "United States",
    job_min_salary: 60000,
    job_max_salary: 95000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.hok.com/careers/42",
    job_posted_at_datetime_utc: "2024-01-15T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Degree in Interior Design",
        "AutoCAD/SketchUp skills",
        "Portfolio required",
      ],
      Responsibilities: [
        "Space planning",
        "Material selection",
        "Client presentations",
      ],
    },
  },
  {
    job_id: "43",
    job_title: "Forensic Scientist",
    employer_name: "FBI",
    employer_logo: "https://logo.clearbit.com/fbi.gov",
    job_description:
      "Analyze evidence for federal criminal investigations. Perform DNA analysis, toxicology tests, and crime scene reconstruction.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Quantico",
    job_country: "United States",
    job_min_salary: 70000,
    job_max_salary: 110000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.fbijobs.gov/43",
    job_posted_at_datetime_utc: "2024-01-20T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Degree in Forensic Science",
        "Lab experience",
        "Attention to detail",
      ],
      Responsibilities: [
        "Evidence analysis",
        "Report writing",
        "Expert testimony",
      ],
    },
  },
  {
    job_id: "44",
    job_title: "Music Producer",
    employer_name: "Sony Music",
    employer_logo: "https://logo.clearbit.com/sonymusic.com",
    job_description:
      "Produce recording sessions for emerging artists. Oversee all aspects of music production from arrangement to final mix.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Los Angeles",
    job_country: "United States",
    job_min_salary: 65000,
    job_max_salary: 120000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.sonymusic.com/careers/44",
    job_posted_at_datetime_utc: "2024-01-25T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "5+ years production experience",
        "Pro Tools expertise",
        "Music theory knowledge",
      ],
      Responsibilities: [
        "Session direction",
        "Sound engineering",
        "Artist collaboration",
      ],
    },
  },
  {
    job_id: "45",
    job_title: "Agricultural Scientist",
    employer_name: "Monsanto",
    employer_logo: "https://logo.clearbit.com/monsanto.com",
    job_description:
      "Conduct research to improve crop yields and sustainability. Develop new plant varieties and test agricultural innovations.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "St. Louis",
    job_country: "United States",
    job_min_salary: 75000,
    job_max_salary: 115000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.monsanto.com/careers/45",
    job_posted_at_datetime_utc: "2024-01-30T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "PhD in Agronomy",
        "Research experience",
        "Statistical analysis skills",
      ],
      Responsibilities: [
        "Field trials",
        "Data collection",
        "Scientific publishing",
      ],
    },
  },
  {
    job_id: "46",
    job_title: "Firefighter",
    employer_name: "City of Los Angeles Fire Department",
    employer_logo: "https://logo.clearbit.com/lafd.org",
    job_description:
      "Respond to emergencies including fires, medical calls, and rescues. Protect lives and property through fire suppression and prevention.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Los Angeles",
    job_country: "United States",
    job_min_salary: 60000,
    job_max_salary: 100000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.joinlafd.org/46",
    job_posted_at_datetime_utc: "2024-02-05T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Fire Academy certification",
        "EMT certification",
        "Physical fitness",
      ],
      Responsibilities: [
        "Emergency response",
        "Equipment maintenance",
        "Public education",
      ],
    },
  },
  {
    job_id: "47",
    job_title: "Museum Curator",
    employer_name: "Smithsonian Institution",
    employer_logo: "https://logo.clearbit.com/si.edu",
    job_description:
      "Manage art collections and develop exhibitions for a world-renowned museum. Conduct research and acquire new pieces for the permanent collection.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Washington DC",
    job_country: "United States",
    job_min_salary: 65000,
    job_max_salary: 95000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.si.edu/careers/47",
    job_posted_at_datetime_utc: "2024-02-10T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "MA in Art History",
        "5+ years curatorial experience",
        "Specialized knowledge",
      ],
      Responsibilities: [
        "Exhibition planning",
        "Collection management",
        "Research publication",
      ],
    },
  },
  {
    job_id: "48",
    job_title: "Speech Language Pathologist",
    employer_name: "Kaiser Permanente",
    employer_logo: "https://logo.clearbit.com/kaiserpermanente.org",
    job_description:
      "Assess and treat communication disorders in pediatric and adult patients. Develop individualized therapy plans and track progress.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Oakland",
    job_country: "United States",
    job_min_salary: 75000,
    job_max_salary: 105000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.kaiserpermanentejobs.org/48",
    job_posted_at_datetime_utc: "2024-02-15T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Master's in SLP",
        "State licensure",
        "ASHA certification",
      ],
      Responsibilities: [
        "Patient evaluations",
        "Therapy sessions",
        "Caregiver education",
      ],
    },
  },
  {
    job_id: "49",
    job_title: "Urban Planner",
    employer_name: "AECOM",
    employer_logo: "https://logo.clearbit.com/aecom.com",
    job_description:
      "Develop comprehensive plans for urban development projects. Analyze land use patterns and recommend zoning policies.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Chicago",
    job_country: "United States",
    job_min_salary: 70000,
    job_max_salary: 100000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.aecom.com/careers/49",
    job_posted_at_datetime_utc: "2024-02-20T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Master's in Urban Planning",
        "GIS proficiency",
        "Public engagement experience",
      ],
      Responsibilities: [
        "Site analysis",
        "Policy development",
        "Stakeholder coordination",
      ],
    },
  },
  {
    job_id: "50",
    job_title: "Professional Athlete",
    employer_name: "Los Angeles Lakers",
    employer_logo: "https://logo.clearbit.com/nba.com/lakers",
    job_description:
      "Compete at the highest level of professional basketball. Maintain peak physical condition and represent the organization professionally.",
    job_employment_type: "FULLTIME",
    job_is_remote: false,
    job_city: "Los Angeles",
    job_country: "United States",
    job_min_salary: 1000000,
    job_max_salary: 40000000,
    job_salary_currency: "USD",
    job_apply_link: "https://www.nba.com/lakers/careers/50",
    job_posted_at_datetime_utc: "2024-02-25T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Elite basketball skills",
        "Professional experience",
        "Team player mentality",
      ],
      Responsibilities: [
        "Game performance",
        "Media obligations",
        "Community appearances",
      ],
    },
  },
  {
    job_id: "61",
    job_title: "Marketing Intern",
    employer_name: "Nike",
    employer_logo: "https://logo.clearbit.com/nike.com",
    job_description:
      "Support the marketing team with campaign execution, social media management, and market research.",
    job_employment_type: "INTERNSHIP",
    job_is_remote: false,
    job_city: "Portland",
    job_country: "United States",
    job_min_salary: 20,
    job_max_salary: 22,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://jobs.nike.com/61",
    job_posted_at_datetime_utc: "2024-04-20T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Marketing major preferred",
        "Social media experience",
        "Creative thinking",
      ],
      Responsibilities: [
        "Campaign support",
        "Content creation",
        "Data analysis",
      ],
    },
  },
  {
    job_id: "62",
    job_title: "Software Engineering Intern",
    employer_name: "SpaceX",
    employer_logo: "https://logo.clearbit.com/spacex.com",
    job_description:
      "Work alongside engineers to develop software solutions for spaceflight systems and mission operations.",
    job_employment_type: "INTERNSHIP",
    job_is_remote: false,
    job_city: "Hawthorne",
    job_country: "United States",
    job_min_salary: 35,
    job_max_salary: 40,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://www.spacex.com/careers/62",
    job_posted_at_datetime_utc: "2024-04-25T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "CS/Engineering student",
        "Python/C++ skills",
        "Passion for aerospace",
      ],
      Responsibilities: [
        "Code development",
        "Testing support",
        "Documentation",
      ],
    },
  },
  {
    job_id: "63",
    job_title: "Architecture Intern",
    employer_name: "Skidmore, Owings & Merrill",
    employer_logo: "https://logo.clearbit.com/som.com",
    job_description:
      "Assist with architectural drawings, 3D modeling, and project research for high-profile design projects.",
    job_employment_type: "INTERNSHIP",
    job_is_remote: false,
    job_city: "Chicago",
    job_country: "United States",
    job_min_salary: 22,
    job_max_salary: 25,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://www.som.com/careers/63",
    job_posted_at_datetime_utc: "2024-05-01T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Architecture student",
        "Revit proficiency",
        "Portfolio required",
      ],
      Responsibilities: [
        "Drafting support",
        "Model development",
        "Material research",
      ],
    },
  },
  {
    job_id: "64",
    job_title: "Biomedical Research Intern",
    employer_name: "Mayo Clinic",
    employer_logo: "https://logo.clearbit.com/mayoclinic.org",
    job_description:
      "Assist with laboratory research in cancer immunology, including data collection and analysis.",
    job_employment_type: "INTERNSHIP",
    job_is_remote: false,
    job_city: "Rochester",
    job_country: "United States",
    job_min_salary: 18,
    job_max_salary: 20,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://jobs.mayoclinic.org/64",
    job_posted_at_datetime_utc: "2024-05-05T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Biology/Chemistry major",
        "Lab course experience",
        "Attention to detail",
      ],
      Responsibilities: [
        "Experiment assistance",
        "Data recording",
        "Literature reviews",
      ],
    },
  },
  {
    job_id: "65",
    job_title: "Investment Banking Summer Analyst",
    employer_name: "Goldman Sachs",
    employer_logo: "https://logo.clearbit.com/goldmansachs.com",
    job_description:
      "Summer internship program providing exposure to financial modeling, valuation, and transaction execution.",
    job_employment_type: "INTERNSHIP",
    job_is_remote: false,
    job_city: "New York",
    job_country: "United States",
    job_min_salary: 45,
    job_max_salary: 50,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://www.goldmansachs.com/careers/65",
    job_posted_at_datetime_utc: "2024-05-10T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Finance/Economics major",
        "Excel proficiency",
        "Strong analytical skills",
      ],
      Responsibilities: [
        "Financial analysis",
        "Presentation preparation",
        "Market research",
      ],
    },
  },
  {
    job_id: "66",
    job_title: "Environmental Policy Intern",
    employer_name: "World Wildlife Fund",
    employer_logo: "https://logo.clearbit.com/worldwildlife.org",
    job_description:
      "Research environmental policies and assist with advocacy campaigns to protect endangered species.",
    job_employment_type: "INTERNSHIP",
    job_is_remote: true,
    job_city: "Washington DC",
    job_country: "United States",
    job_min_salary: 17,
    job_max_salary: 19,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://www.worldwildlife.org/about/careers/66",
    job_posted_at_datetime_utc: "2024-05-15T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Environmental studies major",
        "Research experience",
        "Policy interest",
      ],
      Responsibilities: [
        "Policy research",
        "Report writing",
        "Stakeholder outreach",
      ],
    },
  },
  {
    job_id: "67",
    job_title: "Fashion Design Intern",
    employer_name: "Ralph Lauren",
    employer_logo: "https://logo.clearbit.com/ralphlauren.com",
    job_description:
      "Assist design team with fabric research, sketching, and sample development for upcoming collections.",
    job_employment_type: "INTERNSHIP",
    job_is_remote: false,
    job_city: "New York",
    job_country: "United States",
    job_min_salary: 18,
    job_max_salary: 20,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://careers.ralphlauren.com/67",
    job_posted_at_datetime_utc: "2024-05-20T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Fashion design student",
        "Illustration skills",
        "Sewing ability",
      ],
      Responsibilities: [
        "Trend research",
        "Design assistance",
        "Sample tracking",
      ],
    },
  },
  {
    job_id: "68",
    job_title: "Journalism Intern",
    employer_name: "CNN",
    employer_logo: "https://logo.clearbit.com/cnn.com",
    job_description:
      "Support newsroom operations including research, fact-checking, and assisting with story development.",
    job_employment_type: "INTERNSHIP",
    job_is_remote: false,
    job_city: "Atlanta",
    job_country: "United States",
    job_min_salary: 16,
    job_max_salary: 18,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://www.warnerbrosdiscovery.com/careers/68",
    job_posted_at_datetime_utc: "2024-05-25T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Journalism/Comms major",
        "Writing samples required",
        "News awareness",
      ],
      Responsibilities: [
        "Research support",
        "Interview assistance",
        "Content production",
      ],
    },
  },
  {
    job_id: "69",
    job_title: "Human Resources Intern",
    employer_name: "Google",
    employer_logo: "https://logo.clearbit.com/google.com",
    job_description:
      "Learn about HR operations including recruitment, employee engagement, and diversity initiatives.",
    job_employment_type: "INTERNSHIP",
    job_is_remote: true,
    job_city: "Mountain View",
    job_country: "United States",
    job_min_salary: 30,
    job_max_salary: 32,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://careers.google.com/69",
    job_posted_at_datetime_utc: "2024-06-01T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "HR/Business major",
        "Interpersonal skills",
        "Confidentiality",
      ],
      Responsibilities: [
        "Recruiting support",
        "Event coordination",
        "Data analysis",
      ],
    },
  },
  {
    job_id: "70",
    job_title: "Film Production Intern",
    employer_name: "Pixar",
    employer_logo: "https://logo.clearbit.com/pixar.com",
    job_description:
      "Assist animation production teams with various aspects of the filmmaking process from storyboarding to post-production.",
    job_employment_type: "INTERNSHIP",
    job_is_remote: false,
    job_city: "Emeryville",
    job_country: "United States",
    job_min_salary: 22,
    job_max_salary: 25,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://www.pixar.com/careers/70",
    job_posted_at_datetime_utc: "2024-06-05T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Film/Animation student",
        "Creative portfolio",
        "Team player",
      ],
      Responsibilities: [
        "Production assistance",
        "Asset organization",
        "Creative input",
      ],
    },
  },
  {
    job_id: "51",
    job_title: "Barista",
    employer_name: "Starbucks",
    employer_logo: "https://logo.clearbit.com/starbucks.com",
    job_description:
      "Prepare and serve premium coffee beverages while providing exceptional customer service in a fast-paced environment.",
    job_employment_type: "PARTTIME",
    job_is_remote: false,
    job_city: "Seattle",
    job_country: "United States",
    job_min_salary: 15,
    job_max_salary: 18,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://careers.starbucks.com/51",
    job_posted_at_datetime_utc: "2024-03-01T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "No experience required",
        "Ability to work weekends",
        "Customer service orientation",
      ],
      Responsibilities: [
        "Beverage preparation",
        "Cash handling",
        "Store cleanliness",
      ],
    },
  },
  {
    job_id: "52",
    job_title: "Library Assistant",
    employer_name: "New York Public Library",
    employer_logo: "https://logo.clearbit.com/nypl.org",
    job_description:
      "Assist patrons with locating materials, checking out books, and supporting library programs and events.",
    job_employment_type: "PARTTIME",
    job_is_remote: false,
    job_city: "New York",
    job_country: "United States",
    job_min_salary: 18,
    job_max_salary: 22,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://www.nypl.org/careers/52",
    job_posted_at_datetime_utc: "2024-03-05T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "High school diploma",
        "Organizational skills",
        "Basic computer proficiency",
      ],
      Responsibilities: [
        "Book circulation",
        "Shelf organization",
        "Program support",
      ],
    },
  },
  {
    job_id: "53",
    job_title: "Fitness Instructor",
    employer_name: "24 Hour Fitness",
    employer_logo: "https://logo.clearbit.com/24hourfitness.com",
    job_description:
      "Lead group fitness classes and provide instruction on proper exercise techniques to ensure member safety.",
    job_employment_type: "PARTTIME",
    job_is_remote: false,
    job_city: "Los Angeles",
    job_country: "United States",
    job_min_salary: 25,
    job_max_salary: 40,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://www.24hourfitness.com/careers/53",
    job_posted_at_datetime_utc: "2024-03-10T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Certification in specialty area",
        "CPR/AED certified",
        "Enthusiastic personality",
      ],
      Responsibilities: [
        "Class instruction",
        "Equipment setup",
        "Member engagement",
      ],
    },
  },
  {
    job_id: "54",
    job_title: "Tutor",
    employer_name: "Kumon",
    employer_logo: "https://logo.clearbit.com/kumon.com",
    job_description:
      "Provide academic support to students in math and reading using the Kumon Method during after-school hours.",
    job_employment_type: "PARTTIME",
    job_is_remote: false,
    job_city: "Chicago",
    job_country: "United States",
    job_min_salary: 16,
    job_max_salary: 20,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://www.kumon.com/careers/54",
    job_posted_at_datetime_utc: "2024-03-15T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Strong math/reading skills",
        "Patience with children",
        "Afternoon availability",
      ],
      Responsibilities: [
        "Student instruction",
        "Progress tracking",
        "Parent communication",
      ],
    },
  },
  {
    job_id: "55",
    job_title: "Retail Associate",
    employer_name: "Apple Store",
    employer_logo: "https://logo.clearbit.com/apple.com",
    job_description:
      "Provide technical support and product knowledge to customers in an Apple retail store environment.",
    job_employment_type: "PARTTIME",
    job_is_remote: false,
    job_city: "San Francisco",
    job_country: "United States",
    job_min_salary: 22,
    job_max_salary: 26,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://www.apple.com/careers/us/retail/55",
    job_posted_at_datetime_utc: "2024-03-20T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Tech enthusiasm",
        "Weekend availability",
        "Problem-solving skills",
      ],
      Responsibilities: [
        "Customer assistance",
        "Product demonstrations",
        "Inventory management",
      ],
    },
  },
  {
    job_id: "56",
    job_title: "Delivery Driver",
    employer_name: "UPS",
    employer_logo: "https://logo.clearbit.com/ups.com",
    job_description:
      "Package delivery and pickup on an assigned route, providing excellent customer service.",
    job_employment_type: "PARTTIME",
    job_is_remote: false,
    job_city: "Dallas",
    job_country: "United States",
    job_min_salary: 21,
    job_max_salary: 24,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://www.jobs-ups.com/56",
    job_posted_at_datetime_utc: "2024-03-25T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Clean driving record",
        "Ability to lift 70 lbs",
        "Navigation skills",
      ],
      Responsibilities: [
        "Timely deliveries",
        "Package handling",
        "Customer interaction",
      ],
    },
  },
  {
    job_id: "57",
    job_title: "Campus Tour Guide",
    employer_name: "Harvard University",
    employer_logo: "https://logo.clearbit.com/harvard.edu",
    job_description:
      "Lead informative and engaging campus tours for prospective students and visitors.",
    job_employment_type: "PARTTIME",
    job_is_remote: false,
    job_city: "Cambridge",
    job_country: "United States",
    job_min_salary: 18,
    job_max_salary: 20,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://hr.harvard.edu/jobs/57",
    job_posted_at_datetime_utc: "2024-04-01T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Current student preferred",
        "Public speaking skills",
        "School spirit",
      ],
      Responsibilities: ["Tour leadership", "Q&A sessions", "Event support"],
    },
  },
  {
    job_id: "58",
    job_title: "Bookkeeper",
    employer_name: "H&R Block",
    employer_logo: "https://logo.clearbit.com/hrblock.com",
    job_description:
      "Provide part-time bookkeeping services for small business clients, maintaining financial records.",
    job_employment_type: "PARTTIME",
    job_is_remote: true,
    job_city: "Kansas City",
    job_country: "United States",
    job_min_salary: 25,
    job_max_salary: 30,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://www.hrblock.com/careers/58",
    job_posted_at_datetime_utc: "2024-04-05T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Accounting coursework",
        "QuickBooks proficiency",
        "Attention to detail",
      ],
      Responsibilities: [
        "Accounts reconciliation",
        "Expense tracking",
        "Report generation",
      ],
    },
  },
  {
    job_id: "59",
    job_title: "Social Media Assistant",
    employer_name: "BuzzFeed",
    employer_logo: "https://logo.clearbit.com/buzzfeed.com",
    job_description:
      "Create and schedule social media content across platforms, engaging with followers and analyzing metrics.",
    job_employment_type: "PARTTIME",
    job_is_remote: true,
    job_city: "New York",
    job_country: "United States",
    job_min_salary: 20,
    job_max_salary: 25,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://www.buzzfeed.com/careers/59",
    job_posted_at_datetime_utc: "2024-04-10T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "Social media savvy",
        "Content creation skills",
        "Evening availability",
      ],
      Responsibilities: [
        "Content scheduling",
        "Community engagement",
        "Trend monitoring",
      ],
    },
  },
  {
    job_id: "60",
    job_title: "Pharmacy Technician",
    employer_name: "CVS Health",
    employer_logo: "https://logo.clearbit.com/cvs.com",
    job_description:
      "Assist pharmacists with prescription processing and customer service in a retail pharmacy setting.",
    job_employment_type: "PARTTIME",
    job_is_remote: false,
    job_city: "Boston",
    job_country: "United States",
    job_min_salary: 18,
    job_max_salary: 22,
    job_salary_currency: "USD",
    job_salary_period: "hour",
    job_apply_link: "https://jobs.cvshealth.com/60",
    job_posted_at_datetime_utc: "2024-04-15T09:00:00Z",
    job_highlights: {
      Qualifications: [
        "State certification",
        "Accuracy with medications",
        "HIPAA knowledge",
      ],
      Responsibilities: [
        "Prescription processing",
        "Inventory management",
        "Customer service",
      ],
    },
  },
];
